//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassAct.Website.Pl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClassActDBEntities : DbContext
    {
        public ClassActDBEntities()
            : base("name=ClassActDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblResturant> tblResturants { get; set; }
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblFeature> tblFeatures { get; set; }
        public virtual DbSet<tblPerson> tblPersons { get; set; }
        public virtual DbSet<tblPersonAddress> tblPersonAddresses { get; set; }
        public virtual DbSet<tblPersonFeaturePreference> tblPersonFeaturePreferences { get; set; }
        public virtual DbSet<tblPersonRelationship> tblPersonRelationships { get; set; }
        public virtual DbSet<tblPersonResturantFeatureResturant> tblPersonResturantFeatureResturants { get; set; }
        public virtual DbSet<tblRelationshipsLookUp> tblRelationshipsLookUps { get; set; }
        public virtual DbSet<tblResturantFeature> tblResturantFeatures { get; set; }
        public virtual DbSet<tblCuisine> tblCuisines { get; set; }
        public virtual DbSet<tblCuisineResturant> tblCuisineResturants { get; set; }
        public virtual DbSet<tblMeal> tblMeals { get; set; }
        public virtual DbSet<tblPersonCuisine> tblPersonCuisines { get; set; }
    }
}
