//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassAct.Website.Pl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeal
    {
        public int PersonID { get; set; }
        public string ResturantID { get; set; }
        public string CuisineID { get; set; }
        public System.DateTime Date { get; set; }
        public double Rating { get; set; }
    }
}
