//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassAct.Website.Pl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public int PersonID { get; set; }
        public string PersonsEmail { get; set; }
        public string PersonsUserName { get; set; }
        public string PersonsPassword { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonLastName { get; set; }
        public Nullable<System.DateTime> PersonDOB { get; set; }
        public string PersonIncome { get; set; }
    }
}
