//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassAct.Website.Pl
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResturant
    {
        public int ResturantID { get; set; }
        public int AddressID { get; set; }
        public string ResturantName { get; set; }
        public string ResturantImagePath { get; set; }
    }
}
